// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/account/signup": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/crm": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/account/logout" | "/account/signin" | "/account/signup" | "/contact" | "/dashboard" | "/dashboard/crm" | "/faq" | "/pricing" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./account/signup/page.jsx": {
    id: "account/signup/page";
    page: "/account/signup";
  };
  "./contact/page.jsx": {
    id: "contact/page";
    page: "/contact";
  };
  "./dashboard/page.jsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./dashboard/crm/page.jsx": {
    id: "dashboard/crm/page";
    page: "/dashboard/crm";
  };
  "./faq/page.jsx": {
    id: "faq/page";
    page: "/faq";
  };
  "./pricing/page.jsx": {
    id: "pricing/page";
    page: "/pricing";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "account/logout/page": typeof import("./src/app/./account/logout/page.jsx");
  "account/signin/page": typeof import("./src/app/./account/signin/page.jsx");
  "account/signup/page": typeof import("./src/app/./account/signup/page.jsx");
  "contact/page": typeof import("./src/app/./contact/page.jsx");
  "dashboard/page": typeof import("./src/app/./dashboard/page.jsx");
  "dashboard/crm/page": typeof import("./src/app/./dashboard/crm/page.jsx");
  "faq/page": typeof import("./src/app/./faq/page.jsx");
  "pricing/page": typeof import("./src/app/./pricing/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};